spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.5.183.117:3306/blog_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: wsng1994
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: /Users/haidongwang/log
mybatis:
  mapper-locations: classpath:mapper/*/*.xml     # mapper映射文件
  type-aliases-package: com.wyu.tt16clickhouse.entity

clickhouse:
  driverClassName: ru.yandex.clickhouse.ClickHouseDriver
  url: jdbc:clickhouse://121.5.183.117:8123,121.5.183.117:8123/tutorial
  password:
  initialSize: 10
  maxActive: 100
  minIdle: 10
  maxWait: 6000
  user: default

server:
  port: 8081
  servlet:
    context-path: /blog

img:
  path: /Users/haidongwang/Downloads/img/


#logging:
#  config: classpath:logback-spring.xml